import {
  IconBriefcase,
  IconCode,
  IconFolder,
  IconLanguage,
  IconQuote,
  IconSettings,
  IconTool,
  IconUser,
} from '@tabler/icons-react'
import type { AppModuleManifest } from '@/modules/core/types'

export const portfolioModule: AppModuleManifest = {
  id: 'portfolio',
  title: 'Portfolio',
  description: 'Admin dashboard for managing all portfolio content — experiences, skills, projects, testimonials, translations, and site settings.',
  enabledByDefault: true,
  routes: [
    { path: '/dashboard/portfolio', kind: 'page' },
    { path: '/dashboard/portfolio/experiences', kind: 'page' },
    { path: '/dashboard/portfolio/skills', kind: 'page' },
    { path: '/dashboard/portfolio/projects', kind: 'page' },
    { path: '/dashboard/portfolio/services', kind: 'page' },
    { path: '/dashboard/portfolio/testimonials', kind: 'page' },
    { path: '/dashboard/portfolio/content', kind: 'page' },
    { path: '/dashboard/portfolio/translations', kind: 'page' },
  ],
  navigation: [
    {
      id: 'portfolio',
      title: 'Portfolio',
      kind: 'main',
      order: 10,
      items: [
        {
          id: 'portfolio-overview',
          titleKey: 'sidebar.portfolio.overview',
          fallbackTitle: 'Overview',
          icon: IconUser,
          to: '/dashboard/portfolio',
          order: 10,
        },
        {
          id: 'portfolio-experiences',
          titleKey: 'sidebar.portfolio.experiences',
          fallbackTitle: 'Experiences',
          icon: IconBriefcase,
          to: '/dashboard/portfolio/experiences',
          order: 20,
        },
        {
          id: 'portfolio-skills',
          titleKey: 'sidebar.portfolio.skills',
          fallbackTitle: 'Skills & Tech',
          icon: IconCode,
          to: '/dashboard/portfolio/skills',
          order: 30,
        },
        {
          id: 'portfolio-projects',
          titleKey: 'sidebar.portfolio.projects',
          fallbackTitle: 'Projects',
          icon: IconFolder,
          to: '/dashboard/portfolio/projects',
          order: 40,
        },
        {
          id: 'portfolio-services',
          titleKey: 'sidebar.portfolio.services',
          fallbackTitle: 'Services',
          icon: IconTool,
          to: '/dashboard/portfolio/services',
          order: 45,
        },
        {
          id: 'portfolio-testimonials',
          titleKey: 'sidebar.portfolio.testimonials',
          fallbackTitle: 'Testimonials',
          icon: IconQuote,
          to: '/dashboard/portfolio/testimonials',
          order: 50,
        },
        {
          id: 'portfolio-content',
          titleKey: 'sidebar.portfolio.content',
          fallbackTitle: 'Content Blocks',
          icon: IconSettings,
          to: '/dashboard/portfolio/content',
          order: 60,
        },
        {
          id: 'portfolio-translations',
          titleKey: 'sidebar.portfolio.translations',
          fallbackTitle: 'Translations',
          icon: IconLanguage,
          to: '/dashboard/portfolio/translations',
          order: 70,
        },
      ],
    },
  ],
}
