/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DashboardDashboardRouteRouteImport } from './routes/_dashboard/dashboard/route'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiTestConnectionRouteImport } from './routes/api/ai/test-connection'
import { Route as ApiAiStatusRouteImport } from './routes/api/ai/status'
import { Route as ApiAiSearchRouteImport } from './routes/api/ai/search'
import { Route as ApiAiParseFileRouteImport } from './routes/api/ai/parse-file'
import { Route as ApiAiModelsRouteImport } from './routes/api/ai/models'
import { Route as ApiAiConfigStoreRouteImport } from './routes/api/ai/config-store'
import { Route as ApiAiAuditRouteImport } from './routes/api/ai/audit'
import { Route as DashboardDashboardUsersRouteImport } from './routes/_dashboard/dashboard/users'
import { Route as DashboardDashboardHelpRouteImport } from './routes/_dashboard/dashboard/help'
import { Route as ApiAiChatRouteRouteImport } from './routes/api/ai/chat/route'
import { Route as DashboardDashboardSettingsRouteRouteImport } from './routes/_dashboard/dashboard/settings/route'
import { Route as DashboardDashboardSettingsIndexRouteImport } from './routes/_dashboard/dashboard/settings/index'
import { Route as DashboardDashboardPortfolioIndexRouteImport } from './routes/_dashboard/dashboard/portfolio/index'
import { Route as ApiAiChatCompletionsRouteImport } from './routes/api/ai/chat/completions'
import { Route as DashboardDashboardSettingsSystemRouteImport } from './routes/_dashboard/dashboard/settings/system'
import { Route as DashboardDashboardSettingsSiteRouteImport } from './routes/_dashboard/dashboard/settings/site'
import { Route as DashboardDashboardSettingsIa_configRouteImport } from './routes/_dashboard/dashboard/settings/ia_config'
import { Route as DashboardDashboardPortfolioTranslationsRouteImport } from './routes/_dashboard/dashboard/portfolio/translations'
import { Route as DashboardDashboardPortfolioTestimonialsRouteImport } from './routes/_dashboard/dashboard/portfolio/testimonials'
import { Route as DashboardDashboardPortfolioSkillsRouteImport } from './routes/_dashboard/dashboard/portfolio/skills'
import { Route as DashboardDashboardPortfolioServicesRouteImport } from './routes/_dashboard/dashboard/portfolio/services'
import { Route as DashboardDashboardPortfolioProjectsRouteImport } from './routes/_dashboard/dashboard/portfolio/projects'
import { Route as DashboardDashboardPortfolioExperiencesRouteImport } from './routes/_dashboard/dashboard/portfolio/experiences'
import { Route as DashboardDashboardPortfolioContentRouteImport } from './routes/_dashboard/dashboard/portfolio/content'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRouteRoute = DashboardDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTestConnectionRoute = ApiAiTestConnectionRouteImport.update({
  id: '/api/ai/test-connection',
  path: '/api/ai/test-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStatusRoute = ApiAiStatusRouteImport.update({
  id: '/api/ai/status',
  path: '/api/ai/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSearchRoute = ApiAiSearchRouteImport.update({
  id: '/api/ai/search',
  path: '/api/ai/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiParseFileRoute = ApiAiParseFileRouteImport.update({
  id: '/api/ai/parse-file',
  path: '/api/ai/parse-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiModelsRoute = ApiAiModelsRouteImport.update({
  id: '/api/ai/models',
  path: '/api/ai/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConfigStoreRoute = ApiAiConfigStoreRouteImport.update({
  id: '/api/ai/config-store',
  path: '/api/ai/config-store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAuditRoute = ApiAiAuditRouteImport.update({
  id: '/api/ai/audit',
  path: '/api/ai/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardUsersRoute = DashboardDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardDashboardRouteRoute,
} as any)
const DashboardDashboardHelpRoute = DashboardDashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardDashboardRouteRoute,
} as any)
const ApiAiChatRouteRoute = ApiAiChatRouteRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardSettingsRouteRoute =
  DashboardDashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardSettingsIndexRoute =
  DashboardDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardSettingsRouteRoute,
  } as any)
const DashboardDashboardPortfolioIndexRoute =
  DashboardDashboardPortfolioIndexRouteImport.update({
    id: '/portfolio/',
    path: '/portfolio/',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const ApiAiChatCompletionsRoute = ApiAiChatCompletionsRouteImport.update({
  id: '/completions',
  path: '/completions',
  getParentRoute: () => ApiAiChatRouteRoute,
} as any)
const DashboardDashboardSettingsSystemRoute =
  DashboardDashboardSettingsSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => DashboardDashboardSettingsRouteRoute,
  } as any)
const DashboardDashboardSettingsSiteRoute =
  DashboardDashboardSettingsSiteRouteImport.update({
    id: '/site',
    path: '/site',
    getParentRoute: () => DashboardDashboardSettingsRouteRoute,
  } as any)
const DashboardDashboardSettingsIa_configRoute =
  DashboardDashboardSettingsIa_configRouteImport.update({
    id: '/ia_config',
    path: '/ia_config',
    getParentRoute: () => DashboardDashboardSettingsRouteRoute,
  } as any)
const DashboardDashboardPortfolioTranslationsRoute =
  DashboardDashboardPortfolioTranslationsRouteImport.update({
    id: '/portfolio/translations',
    path: '/portfolio/translations',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardPortfolioTestimonialsRoute =
  DashboardDashboardPortfolioTestimonialsRouteImport.update({
    id: '/portfolio/testimonials',
    path: '/portfolio/testimonials',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardPortfolioSkillsRoute =
  DashboardDashboardPortfolioSkillsRouteImport.update({
    id: '/portfolio/skills',
    path: '/portfolio/skills',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardPortfolioServicesRoute =
  DashboardDashboardPortfolioServicesRouteImport.update({
    id: '/portfolio/services',
    path: '/portfolio/services',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardPortfolioProjectsRoute =
  DashboardDashboardPortfolioProjectsRouteImport.update({
    id: '/portfolio/projects',
    path: '/portfolio/projects',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardPortfolioExperiencesRoute =
  DashboardDashboardPortfolioExperiencesRouteImport.update({
    id: '/portfolio/experiences',
    path: '/portfolio/experiences',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)
const DashboardDashboardPortfolioContentRoute =
  DashboardDashboardPortfolioContentRouteImport.update({
    id: '/portfolio/content',
    path: '/portfolio/content',
    getParentRoute: () => DashboardDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardDashboardRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRouteRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRouteRouteWithChildren
  '/dashboard/help': typeof DashboardDashboardHelpRoute
  '/dashboard/users': typeof DashboardDashboardUsersRoute
  '/api/ai/audit': typeof ApiAiAuditRoute
  '/api/ai/config-store': typeof ApiAiConfigStoreRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/parse-file': typeof ApiAiParseFileRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/portfolio/content': typeof DashboardDashboardPortfolioContentRoute
  '/dashboard/portfolio/experiences': typeof DashboardDashboardPortfolioExperiencesRoute
  '/dashboard/portfolio/projects': typeof DashboardDashboardPortfolioProjectsRoute
  '/dashboard/portfolio/services': typeof DashboardDashboardPortfolioServicesRoute
  '/dashboard/portfolio/skills': typeof DashboardDashboardPortfolioSkillsRoute
  '/dashboard/portfolio/testimonials': typeof DashboardDashboardPortfolioTestimonialsRoute
  '/dashboard/portfolio/translations': typeof DashboardDashboardPortfolioTranslationsRoute
  '/dashboard/settings/ia_config': typeof DashboardDashboardSettingsIa_configRoute
  '/dashboard/settings/site': typeof DashboardDashboardSettingsSiteRoute
  '/dashboard/settings/system': typeof DashboardDashboardSettingsSystemRoute
  '/api/ai/chat/completions': typeof ApiAiChatCompletionsRoute
  '/dashboard/portfolio/': typeof DashboardDashboardPortfolioIndexRoute
  '/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/api/ai/chat': typeof ApiAiChatRouteRouteWithChildren
  '/dashboard/help': typeof DashboardDashboardHelpRoute
  '/dashboard/users': typeof DashboardDashboardUsersRoute
  '/api/ai/audit': typeof ApiAiAuditRoute
  '/api/ai/config-store': typeof ApiAiConfigStoreRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/parse-file': typeof ApiAiParseFileRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/portfolio/content': typeof DashboardDashboardPortfolioContentRoute
  '/dashboard/portfolio/experiences': typeof DashboardDashboardPortfolioExperiencesRoute
  '/dashboard/portfolio/projects': typeof DashboardDashboardPortfolioProjectsRoute
  '/dashboard/portfolio/services': typeof DashboardDashboardPortfolioServicesRoute
  '/dashboard/portfolio/skills': typeof DashboardDashboardPortfolioSkillsRoute
  '/dashboard/portfolio/testimonials': typeof DashboardDashboardPortfolioTestimonialsRoute
  '/dashboard/portfolio/translations': typeof DashboardDashboardPortfolioTranslationsRoute
  '/dashboard/settings/ia_config': typeof DashboardDashboardSettingsIa_configRoute
  '/dashboard/settings/site': typeof DashboardDashboardSettingsSiteRoute
  '/dashboard/settings/system': typeof DashboardDashboardSettingsSystemRoute
  '/api/ai/chat/completions': typeof ApiAiChatCompletionsRoute
  '/dashboard/portfolio': typeof DashboardDashboardPortfolioIndexRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_landing/': typeof LandingIndexRoute
  '/_dashboard/dashboard/settings': typeof DashboardDashboardSettingsRouteRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRouteRouteWithChildren
  '/_dashboard/dashboard/help': typeof DashboardDashboardHelpRoute
  '/_dashboard/dashboard/users': typeof DashboardDashboardUsersRoute
  '/api/ai/audit': typeof ApiAiAuditRoute
  '/api/ai/config-store': typeof ApiAiConfigStoreRoute
  '/api/ai/models': typeof ApiAiModelsRoute
  '/api/ai/parse-file': typeof ApiAiParseFileRoute
  '/api/ai/search': typeof ApiAiSearchRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/portfolio/content': typeof DashboardDashboardPortfolioContentRoute
  '/_dashboard/dashboard/portfolio/experiences': typeof DashboardDashboardPortfolioExperiencesRoute
  '/_dashboard/dashboard/portfolio/projects': typeof DashboardDashboardPortfolioProjectsRoute
  '/_dashboard/dashboard/portfolio/services': typeof DashboardDashboardPortfolioServicesRoute
  '/_dashboard/dashboard/portfolio/skills': typeof DashboardDashboardPortfolioSkillsRoute
  '/_dashboard/dashboard/portfolio/testimonials': typeof DashboardDashboardPortfolioTestimonialsRoute
  '/_dashboard/dashboard/portfolio/translations': typeof DashboardDashboardPortfolioTranslationsRoute
  '/_dashboard/dashboard/settings/ia_config': typeof DashboardDashboardSettingsIa_configRoute
  '/_dashboard/dashboard/settings/site': typeof DashboardDashboardSettingsSiteRoute
  '/_dashboard/dashboard/settings/system': typeof DashboardDashboardSettingsSystemRoute
  '/api/ai/chat/completions': typeof ApiAiChatCompletionsRoute
  '/_dashboard/dashboard/portfolio/': typeof DashboardDashboardPortfolioIndexRoute
  '/_dashboard/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/health'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/settings'
    | '/api/ai/chat'
    | '/dashboard/help'
    | '/dashboard/users'
    | '/api/ai/audit'
    | '/api/ai/config-store'
    | '/api/ai/models'
    | '/api/ai/parse-file'
    | '/api/ai/search'
    | '/api/ai/status'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/dashboard/'
    | '/dashboard/portfolio/content'
    | '/dashboard/portfolio/experiences'
    | '/dashboard/portfolio/projects'
    | '/dashboard/portfolio/services'
    | '/dashboard/portfolio/skills'
    | '/dashboard/portfolio/testimonials'
    | '/dashboard/portfolio/translations'
    | '/dashboard/settings/ia_config'
    | '/dashboard/settings/site'
    | '/dashboard/settings/system'
    | '/api/ai/chat/completions'
    | '/dashboard/portfolio/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/health'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/api/ai/chat'
    | '/dashboard/help'
    | '/dashboard/users'
    | '/api/ai/audit'
    | '/api/ai/config-store'
    | '/api/ai/models'
    | '/api/ai/parse-file'
    | '/api/ai/search'
    | '/api/ai/status'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/dashboard'
    | '/dashboard/portfolio/content'
    | '/dashboard/portfolio/experiences'
    | '/dashboard/portfolio/projects'
    | '/dashboard/portfolio/services'
    | '/dashboard/portfolio/skills'
    | '/dashboard/portfolio/testimonials'
    | '/dashboard/portfolio/translations'
    | '/dashboard/settings/ia_config'
    | '/dashboard/settings/site'
    | '/dashboard/settings/system'
    | '/api/ai/chat/completions'
    | '/dashboard/portfolio'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_landing'
    | '/auth'
    | '/_dashboard/dashboard'
    | '/api/health'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_landing/'
    | '/_dashboard/dashboard/settings'
    | '/api/ai/chat'
    | '/_dashboard/dashboard/help'
    | '/_dashboard/dashboard/users'
    | '/api/ai/audit'
    | '/api/ai/config-store'
    | '/api/ai/models'
    | '/api/ai/parse-file'
    | '/api/ai/search'
    | '/api/ai/status'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/portfolio/content'
    | '/_dashboard/dashboard/portfolio/experiences'
    | '/_dashboard/dashboard/portfolio/projects'
    | '/_dashboard/dashboard/portfolio/services'
    | '/_dashboard/dashboard/portfolio/skills'
    | '/_dashboard/dashboard/portfolio/testimonials'
    | '/_dashboard/dashboard/portfolio/translations'
    | '/_dashboard/dashboard/settings/ia_config'
    | '/_dashboard/dashboard/settings/site'
    | '/_dashboard/dashboard/settings/system'
    | '/api/ai/chat/completions'
    | '/_dashboard/dashboard/portfolio/'
    | '/_dashboard/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAiChatRouteRoute: typeof ApiAiChatRouteRouteWithChildren
  ApiAiAuditRoute: typeof ApiAiAuditRoute
  ApiAiConfigStoreRoute: typeof ApiAiConfigStoreRoute
  ApiAiModelsRoute: typeof ApiAiModelsRoute
  ApiAiParseFileRoute: typeof ApiAiParseFileRoute
  ApiAiSearchRoute: typeof ApiAiSearchRoute
  ApiAiStatusRoute: typeof ApiAiStatusRoute
  ApiAiTestConnectionRoute: typeof ApiAiTestConnectionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/test-connection': {
      id: '/api/ai/test-connection'
      path: '/api/ai/test-connection'
      fullPath: '/api/ai/test-connection'
      preLoaderRoute: typeof ApiAiTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/status': {
      id: '/api/ai/status'
      path: '/api/ai/status'
      fullPath: '/api/ai/status'
      preLoaderRoute: typeof ApiAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/search': {
      id: '/api/ai/search'
      path: '/api/ai/search'
      fullPath: '/api/ai/search'
      preLoaderRoute: typeof ApiAiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/parse-file': {
      id: '/api/ai/parse-file'
      path: '/api/ai/parse-file'
      fullPath: '/api/ai/parse-file'
      preLoaderRoute: typeof ApiAiParseFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/models': {
      id: '/api/ai/models'
      path: '/api/ai/models'
      fullPath: '/api/ai/models'
      preLoaderRoute: typeof ApiAiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/config-store': {
      id: '/api/ai/config-store'
      path: '/api/ai/config-store'
      fullPath: '/api/ai/config-store'
      preLoaderRoute: typeof ApiAiConfigStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/audit': {
      id: '/api/ai/audit'
      path: '/api/ai/audit'
      fullPath: '/api/ai/audit'
      preLoaderRoute: typeof ApiAiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/users': {
      id: '/_dashboard/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardDashboardUsersRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/help': {
      id: '/_dashboard/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardDashboardHelpRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/settings': {
      id: '/_dashboard/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/settings/': {
      id: '/_dashboard/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardDashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardDashboardSettingsRouteRoute
    }
    '/_dashboard/dashboard/portfolio/': {
      id: '/_dashboard/dashboard/portfolio/'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio/'
      preLoaderRoute: typeof DashboardDashboardPortfolioIndexRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/api/ai/chat/completions': {
      id: '/api/ai/chat/completions'
      path: '/completions'
      fullPath: '/api/ai/chat/completions'
      preLoaderRoute: typeof ApiAiChatCompletionsRouteImport
      parentRoute: typeof ApiAiChatRouteRoute
    }
    '/_dashboard/dashboard/settings/system': {
      id: '/_dashboard/dashboard/settings/system'
      path: '/system'
      fullPath: '/dashboard/settings/system'
      preLoaderRoute: typeof DashboardDashboardSettingsSystemRouteImport
      parentRoute: typeof DashboardDashboardSettingsRouteRoute
    }
    '/_dashboard/dashboard/settings/site': {
      id: '/_dashboard/dashboard/settings/site'
      path: '/site'
      fullPath: '/dashboard/settings/site'
      preLoaderRoute: typeof DashboardDashboardSettingsSiteRouteImport
      parentRoute: typeof DashboardDashboardSettingsRouteRoute
    }
    '/_dashboard/dashboard/settings/ia_config': {
      id: '/_dashboard/dashboard/settings/ia_config'
      path: '/ia_config'
      fullPath: '/dashboard/settings/ia_config'
      preLoaderRoute: typeof DashboardDashboardSettingsIa_configRouteImport
      parentRoute: typeof DashboardDashboardSettingsRouteRoute
    }
    '/_dashboard/dashboard/portfolio/translations': {
      id: '/_dashboard/dashboard/portfolio/translations'
      path: '/portfolio/translations'
      fullPath: '/dashboard/portfolio/translations'
      preLoaderRoute: typeof DashboardDashboardPortfolioTranslationsRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/portfolio/testimonials': {
      id: '/_dashboard/dashboard/portfolio/testimonials'
      path: '/portfolio/testimonials'
      fullPath: '/dashboard/portfolio/testimonials'
      preLoaderRoute: typeof DashboardDashboardPortfolioTestimonialsRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/portfolio/skills': {
      id: '/_dashboard/dashboard/portfolio/skills'
      path: '/portfolio/skills'
      fullPath: '/dashboard/portfolio/skills'
      preLoaderRoute: typeof DashboardDashboardPortfolioSkillsRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/portfolio/services': {
      id: '/_dashboard/dashboard/portfolio/services'
      path: '/portfolio/services'
      fullPath: '/dashboard/portfolio/services'
      preLoaderRoute: typeof DashboardDashboardPortfolioServicesRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/portfolio/projects': {
      id: '/_dashboard/dashboard/portfolio/projects'
      path: '/portfolio/projects'
      fullPath: '/dashboard/portfolio/projects'
      preLoaderRoute: typeof DashboardDashboardPortfolioProjectsRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/portfolio/experiences': {
      id: '/_dashboard/dashboard/portfolio/experiences'
      path: '/portfolio/experiences'
      fullPath: '/dashboard/portfolio/experiences'
      preLoaderRoute: typeof DashboardDashboardPortfolioExperiencesRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
    '/_dashboard/dashboard/portfolio/content': {
      id: '/_dashboard/dashboard/portfolio/content'
      path: '/portfolio/content'
      fullPath: '/dashboard/portfolio/content'
      preLoaderRoute: typeof DashboardDashboardPortfolioContentRouteImport
      parentRoute: typeof DashboardDashboardRouteRoute
    }
  }
}

interface DashboardDashboardSettingsRouteRouteChildren {
  DashboardDashboardSettingsIa_configRoute: typeof DashboardDashboardSettingsIa_configRoute
  DashboardDashboardSettingsSiteRoute: typeof DashboardDashboardSettingsSiteRoute
  DashboardDashboardSettingsSystemRoute: typeof DashboardDashboardSettingsSystemRoute
  DashboardDashboardSettingsIndexRoute: typeof DashboardDashboardSettingsIndexRoute
}

const DashboardDashboardSettingsRouteRouteChildren: DashboardDashboardSettingsRouteRouteChildren =
  {
    DashboardDashboardSettingsIa_configRoute:
      DashboardDashboardSettingsIa_configRoute,
    DashboardDashboardSettingsSiteRoute: DashboardDashboardSettingsSiteRoute,
    DashboardDashboardSettingsSystemRoute:
      DashboardDashboardSettingsSystemRoute,
    DashboardDashboardSettingsIndexRoute: DashboardDashboardSettingsIndexRoute,
  }

const DashboardDashboardSettingsRouteRouteWithChildren =
  DashboardDashboardSettingsRouteRoute._addFileChildren(
    DashboardDashboardSettingsRouteRouteChildren,
  )

interface DashboardDashboardRouteRouteChildren {
  DashboardDashboardSettingsRouteRoute: typeof DashboardDashboardSettingsRouteRouteWithChildren
  DashboardDashboardHelpRoute: typeof DashboardDashboardHelpRoute
  DashboardDashboardUsersRoute: typeof DashboardDashboardUsersRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardPortfolioContentRoute: typeof DashboardDashboardPortfolioContentRoute
  DashboardDashboardPortfolioExperiencesRoute: typeof DashboardDashboardPortfolioExperiencesRoute
  DashboardDashboardPortfolioProjectsRoute: typeof DashboardDashboardPortfolioProjectsRoute
  DashboardDashboardPortfolioServicesRoute: typeof DashboardDashboardPortfolioServicesRoute
  DashboardDashboardPortfolioSkillsRoute: typeof DashboardDashboardPortfolioSkillsRoute
  DashboardDashboardPortfolioTestimonialsRoute: typeof DashboardDashboardPortfolioTestimonialsRoute
  DashboardDashboardPortfolioTranslationsRoute: typeof DashboardDashboardPortfolioTranslationsRoute
  DashboardDashboardPortfolioIndexRoute: typeof DashboardDashboardPortfolioIndexRoute
}

const DashboardDashboardRouteRouteChildren: DashboardDashboardRouteRouteChildren =
  {
    DashboardDashboardSettingsRouteRoute:
      DashboardDashboardSettingsRouteRouteWithChildren,
    DashboardDashboardHelpRoute: DashboardDashboardHelpRoute,
    DashboardDashboardUsersRoute: DashboardDashboardUsersRoute,
    DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
    DashboardDashboardPortfolioContentRoute:
      DashboardDashboardPortfolioContentRoute,
    DashboardDashboardPortfolioExperiencesRoute:
      DashboardDashboardPortfolioExperiencesRoute,
    DashboardDashboardPortfolioProjectsRoute:
      DashboardDashboardPortfolioProjectsRoute,
    DashboardDashboardPortfolioServicesRoute:
      DashboardDashboardPortfolioServicesRoute,
    DashboardDashboardPortfolioSkillsRoute:
      DashboardDashboardPortfolioSkillsRoute,
    DashboardDashboardPortfolioTestimonialsRoute:
      DashboardDashboardPortfolioTestimonialsRoute,
    DashboardDashboardPortfolioTranslationsRoute:
      DashboardDashboardPortfolioTranslationsRoute,
    DashboardDashboardPortfolioIndexRoute:
      DashboardDashboardPortfolioIndexRoute,
  }

const DashboardDashboardRouteRouteWithChildren =
  DashboardDashboardRouteRoute._addFileChildren(
    DashboardDashboardRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardDashboardRouteRoute: typeof DashboardDashboardRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDashboardRouteRoute: DashboardDashboardRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LandingRouteRouteChildren {
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ApiAiChatRouteRouteChildren {
  ApiAiChatCompletionsRoute: typeof ApiAiChatCompletionsRoute
}

const ApiAiChatRouteRouteChildren: ApiAiChatRouteRouteChildren = {
  ApiAiChatCompletionsRoute: ApiAiChatCompletionsRoute,
}

const ApiAiChatRouteRouteWithChildren = ApiAiChatRouteRoute._addFileChildren(
  ApiAiChatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAiChatRouteRoute: ApiAiChatRouteRouteWithChildren,
  ApiAiAuditRoute: ApiAiAuditRoute,
  ApiAiConfigStoreRoute: ApiAiConfigStoreRoute,
  ApiAiModelsRoute: ApiAiModelsRoute,
  ApiAiParseFileRoute: ApiAiParseFileRoute,
  ApiAiSearchRoute: ApiAiSearchRoute,
  ApiAiStatusRoute: ApiAiStatusRoute,
  ApiAiTestConnectionRoute: ApiAiTestConnectionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
